---
- hosts: all
  gather_facts: False
  remote_user: root
  tasks:
    # upload ssh key
    - authorized_key:
        user: root
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
